### ISSUE TITLE
Start and stop sound in example sketches (no autoplay!)

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-website#101]
- [x] We need to dispose of all sound in a sketch when navigating away from a page that has sound. One way to do this would be to use ``window.onhashchange`` https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange. We'd call ``remove()`` which should trigger ``.dispose()`` to get rid of all sounds in the ``p5.soundOut.soundArray``

- Do not auto-play any sound. Should this involve deferring [run_code()](https://github.com/processing/p5.js-website/blob/56f8d473b81a1ea11f3d42249831d785148ee0ab/js/render.js#L13) until a button is pressed? This might be useful for other types of examples that don't involve sound.

cc @omnikrll

**Comment by lmccart** [comment]
is this fixed now?

**Comment by therewasaguy** [comment]
Part 1 is fixed, and part 2 was fixed by updating the examples to only play sound when the canvas is clicked. I think it'd be good to have a better solution in the long run, but we can close for now.
