### ISSUE TITLE
Update hosted library link on Getting Started page with each new version

### ISSUE THREAD

**Issue by valhead** [processing/p5.js-website#102]
The current insturctions on http://p5js.org/get-started/#your-first-sketch are confusing because they ask you to update the URL yourself. It would be easier for beginners if the link was functional and linked to the latest version so they can just copy and paste and get on to making a thing :) 

Currently it should be replaced with: https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.4/p5.min.js

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js-website/commit/1bff9babf1a57bd6813ab24186059ad3ef60ff1f
