### ISSUE TITLE
bug: incorrect language tag for JavaScript

### ISSUE THREAD

**Issue by EshaanAgg** [processing/p5.js-website#106]
In many of the `.mdx` files containing the documentation, the JavaScript code snippets have been marked with the language tag `JavaScript` as follows:
![image](https://github.com/bocoup/p5.js-website/assets/96648934/ec775de6-b960-4e09-ba6f-23df028dfbc4)
This tag is incorrect and should be replaced by `javascript`. These incorrect language tags lead the build by `Shiki` to not be rendered as JS, but rather plaintext:
![image](https://github.com/bocoup/p5.js-website/assets/96648934/671804d9-6f49-4701-93c5-191d9bdf0a73)

A simple global search and replacing `[triple backticks]JavaScript` with `[triple backticks]javascript` should fix the same.

**Comment by EshaanAgg** [comment]
I can take this issue up if the maintainers approve.

**Comment by outofambit** [comment]
just a quick note here that the majority of these are in `src/content/contributor-docs`, which have to be fixed in the p5 repo and then re-imported here with the build contributor docs script. i see a few in `src/content/tutorials`, which can be fixed directly in this repo.

**Comment by limzykenneth** [comment]
For those in contributor docs, we'll fix in the p5.js repo.

**Comment by danicruz0415** [comment]
Hi, I saw this was inactive for some time, so I made a PR. I also noticed that sometimes 4 backticks were used instead of 3 to define code blocks. I fixed both errors, hope it helps 🙈
https://github.com/processing/p5.js/pull/7314
