### ISSUE TITLE
Reference Issue - Table Functions Do Not link to Documentation pages. 

### ISSUE THREAD

**Issue by Luxapodular** [processing/p5.js-website#123]
Hello all! 

For some reason the links in the reference for the Table methods do not link to their documentation pages. Can't figure out why. I'll be running through the source to see if their are any noticeable issues.

**Comment by lmccart** [comment]
hey @Luxapodular there's a general problem with the reference right now, we are working to track it down, but i don't think you need to go through all your changes just yet.

**Comment by lmccart** [comment]
should be good now
