### ISSUE TITLE
Porting Examples/Shape/Load and Display SVG

### ISSUE THREAD

**Issue by mexitalian** [processing/p5.js-website#156]
Am porting [Load and Display SVG](https://processing.org/examples/loaddisplaysvg.html) example.

**Comment by lmccart** [comment]
hi @mexitalian, thanks for volunteering! unfortunately, we don't currently have svg / shape functionality in p5.js.

**Comment by mexitalian** [comment]
The porting search for continues… :)

**Comment by lmccart** [comment]
@shiffman I think you mentioned there were a number of examples that you had actually ported for the processing site that just need to be formatted and added to the p5.js site. Is this correct, are these around somewhere? Maybe this could be a starting place for @mexitalian either to work on adding these, or looking for any wholes.

**Comment by mexitalian** [comment]
@lmccart, @shiffman would be happy to start there, or anywhere.

**Comment by shiffman** [comment]
Indeed!  See this thread:

https://github.com/processing/processing-docs/issues/154

Let me know what else I can do to help.  Oh, also I am in the process of porting all Learning Processing 2nd edition examples to p5.js and you are welcome to any/all of those (but the more "tasty" ones are mostly not there yet.)

https://github.com/shiffman/LearningProcessing-p5.js
