### ISSUE TITLE
js error on reference page

### ISSUE THREAD

**Issue by freder** [processing/p5.js-website#159]
hi,

I just noticed that [http://p5js.org/reference/#/p5.FFT](http://p5js.org/reference/#/p5.FFT) doesn't look like it is supposed to:

![image](https://cloud.githubusercontent.com/assets/724844/9630356/0ee75a70-517a-11e5-94d6-df98aaa4c044.png)

**Comment by lmccart** [comment]
thanks! should be fixed with the latest p5.js lib version update on the site.
