### ISSUE TITLE
typo in windowResized() documentation

### ISSUE THREAD

**Issue by JobLeonard** [processing/p5.js-website#160]
This is a really minor mistake, but might confuse newbies:

http://p5js.org/reference/#p5/windowResized()

> windowResize()()

I think that's one pair of parenthesis too many, no? I'd make the tiny edit myself for a pull-request, but I can't seem to find where the text is stored.

**Comment by lmccart** [comment]
thanks! the fix has been made to the documentation source code that this page is generated from. the corrected version will appear as soon as an updated version of the docs is pushed to the site.
