### ISSUE TITLE
Typo on p5.dom.js reference page

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js-website#161]
Hi,

Just found a small typo on the p5.dom.js reference page (extra square bracket).

![screen shot 2015-09-07 at 12 38 25 pm](https://cloud.githubusercontent.com/assets/7543950/9715980/81103c3e-555d-11e5-9a56-a0e5b8224076.png)

Cheers.

**Comment by lmccart** [comment]
thanks! the fix has been made to the documentation source code that this page is generated from. the corrected version will appear as soon as an updated version of the docs is pushed to the site.
