### ISSUE TITLE
p5.dom.js createCapture() reference problem

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js-website#162]
Hi,

The reference for `createCapture()` for the p5.dom library is a bit messed up since it is trying to render the code which judging from the references for the other functions, is not intended.

[Link to reference](http://p5js.org/reference/#/p5/createCapture)

Safari:
![screen shot 2015-09-12 at 11 05 18 pm](https://cloud.githubusercontent.com/assets/7543950/9834072/98370d80-59a3-11e5-818d-734c8e45ab8a.png)

Chrome:
![screen shot 2015-09-12 at 11 04 57 pm](https://cloud.githubusercontent.com/assets/7543950/9834079/aa2bdc0a-59a3-11e5-8c83-c98bd85d62c0.png)

I can fix it with a PR to p5.js repo if you like.

Cheers.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/907
