### ISSUE TITLE
Reference: should loadImage() be listed with other loadX() functions?

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-website#165]
![screen shot 2015-09-17 at 5 47 29 pm](https://cloud.githubusercontent.com/assets/737638/9930150/58444106-5d64-11e5-8673-2ef5b5adf878.png)

**Comment by lmccart** [comment]
we've generally been following the processing reference. in there, `loadImage()` is listed under image, and `loadFont()` is listed under type. while the load methods associated with files are under input.
https://processing.org/reference/
