### ISSUE TITLE
< symbol next to text with no space causes error in a reference example

### ISSUE THREAD

**Issue by therewasaguy** [processing/p5.js-website#167]
The [log](http://p5js.org/reference/#/p5/log) example gets cut off at this line:

``for(var x=0; x<width; x++) {``

Everything after and including ``<width`` is cut off. It must think it's an html closing tag. If we put some space between ``<`` and ``width`` the example runs just fine:

```
function draw() {
  background(200);
  var maxX = 2.8;
  var maxY = 1.5;
  // Compute the natural log of a value between 0 and maxX
  var xValue = map(mouseX, 0, width, 0, maxX);
  if (xValue > 0) { // Cannot take the log of a negative number.
    var yValue = log(xValue);
    var y = map(yValue, -maxY, maxY, height, 0);
    // Display the calculation occurring.
    var legend = "log(" + nf(xValue, 1, 2) + ")\n= " + nf(yValue, 1, 3);
    stroke(150);
    line(mouseX, y, mouseX, height);
    fill(0);
    text (legend, 5, 15);
    noStroke();
    ellipse (mouseX, y, 7, 7);
  }
  // Draw the log(x) curve,
  // over the domain of x from 0 to maxX
  noFill();
  stroke(0);
  beginShape();
  for(var x=0; x< width; x++) { // <--- adding space*****************
    xValue = map(x, 0, width, 0, maxX);
    yValue = log(xValue);
    y = map(yValue, -maxY, maxY, height, 0);
    vertex(x, y);
  }
  endShape();
  line(0,0,0,height);
  line(0,height/2,width, height/2);
}
```

The problem might just be that the [example closes ``</div>`` before it closes ``</code>``](https://github.com/processing/p5.js/blob/80ab2505443046bcea450d3213af48f8f581b9a6/src/math/calculation.js#L319). Looking into it now

**Comment by therewasaguy** [comment]
Ok, so the problem is that when ``<`` is next to a variable name, like ``width`` or ``height``, it is interpreted as an html closing tag and cuts off the rest of the code. (Changing the order of </div> and </code> didn't help).

I'm not sure where to look to fix this, anybody have some insight? I can take a deeper look later.

**Comment by therewasaguy** [comment]
...still need to find where the HTML is set to begin with in the template. I think it has to do with this https://github.com/processing/p5.js-website/blob/master/reference/assets/js/reference.js#L6934

**Comment by lmccart** [comment]
thanks @therewasaguy! let's look at this together sometime and see if we can find the place it's set and apply the fix.
