### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by gdad-s-river** [processing/p5.js-website#174]
Console error : 
> Uncaught TypeError: Cannot read property 'prototype' of undefined  on p5.dom.js:52

I've included cdn links of p5 dom and p5 libraries and opening a simple example from the website in the browser.

**Comment by lmccart** [comment]
can you please specify which versions of p5.dom.js and p5.js you are using, and the example code you are using.

**Comment by gdad-s-river** [comment]
Sure 
p5.dom.js v0.2.4 , p5.js v0.4.15

html code : 

<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Untitled</title>
        <script src="p5/p5-release/addons/p5.dom.js"></script>
        <script src="p5/p5-release/<p5 class="js"></p5>"></script>
    </head>
    <body>
        
        <script src="main.js"></script>
    </body>
</html>

main.js : 


var canvas;

function setup() {

  canvas = createCanvas(600, 400);

  canvas.position(300, 50);
  canvas.class("lemon");
}

function draw() {

  background(220, 180, 200);
  ellipse(width/2, height/2, 100, 100);
  ellipse(width/4, height/2, 50, 50);
}

**Comment by lmccart** [comment]
looks like there is an error with this line: `<script src="p5/p5-release/<p5 class="js"></p5>"></script>`. also it is a good idea to include p5.js before p5.dom.js though i think either should work.

**Comment by gdad-s-river** [comment]
No wait, I corrected it in my html, even if I use the cdn links, it doesn't work

**Comment by lmccart** [comment]
I'm really sorry, I'm not able to reproduce. This is how I've set up the html:

```html
<html>
  <head>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.15/p5.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.15/addons/p5.dom.js'></script>
    <script src='../lib/addons/p5.sound.js'></script>
    <script src='sketch.js'></script>
    <!-- <style>body{margin: 0; padding: 0}</style> -->
  </head>
  <body><p id="parent">Hello <span id="child">World</span> </p>
  </body>
</html>
```

I'd suggest posting this in the forum which is a better place for debugging questions.
forum.processing.org/two/categories/p5-js

**Comment by gdad-s-river** [comment]
I got it, I got it, I got it by placing p5.js before p5.dom.js :)
