### ISSUE TITLE
specularMaterial() and ambientMaterial() docs crashing page?

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js-website#175]
They seem to be fine in practice, but all 3 browsers are crashing on the [specularMaterial()](http://p5js.org/reference/#/p5/specularMaterial) docs page and the [ambientMaterial()](http://p5js.org/reference/#/p5/ambientMaterial) docs page

**Comment by amejias101** [comment]
what browser are you using? Works fine on my end

**Comment by limzykenneth** [comment]
@amejias101 Sorry but this issue has been fixed, thanks anyway! Can @futuremarc or @lmccart close this? Thanks.
