### ISSUE TITLE
Finding p5.dom reference

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-website#184]
To some extent this may be related to https://github.com/processing/p5.js/issues/645, but I wanted to file an issue here to open a discussion about how the p5.dom and p5.js core references are organized on the site.  I've had several instances in the last week with students not finding the reference pages for functions like `createImg()` (which can in fact be found in the [p5.dom library reference](http://p5js.org/reference/#/libraries/p5.dom)).  There's a [DOM heading on the main reference](http://p5js.org/reference/#group-DOM) but it only includes `p5.Element`.

One quick solution is to just link that DOM heading to the DOM library page.  But perhaps there are other better ideas. Any thoughts?

**Comment by limzykenneth** [comment]
I feel at the moment it requires too many clicks to get to the DOM reference. If p5.dom will be migrated into core then the same should go for the references and if not, at least make it easier to find and access (maybe with the DOM entry in the core reference linking to DOM reference page).

**Comment by lmccart** [comment]
I agree. it will still be a bit before the p5.dom migration, and there's still the issue of finding the p5.sound reference... I think best solution is to link to both directly from the reference page, so it doesn't require so much searching and clicking.
