### ISSUE TITLE
I'm confused by the Frequency Modulation example

### ISSUE THREAD

**Issue by toolness** [processing/p5.js-website#189]
I'm a complete audio beginner so this could easily be my fault, but there are a number of things I find confusing about the [Frequency Modulation example](http://p5js.org/examples/examples/Sound_Frequency_Modulation.php):

* Parts of the page's copy seem to be describing *amplitude* modulation rather than frequency modulation, which makes me wonder if this was originally copy/pasted from the [Amplitude Modulation example](http://p5js.org/examples/examples/Sound_Amplitude_Modulation.php) but not fully updated. For example, the second paragraph states:

  >  The carrier.amp is set to zero because we will have the modulator control its amplitude.

  Yet the actual code sets the `carrier.amp` to `1`, not `0`, and the modulator never seems to touch it.

  At another point, the docs state:

  > a subtle amount of Amplitude Modulation can simulate effects such as Tremolo

  This seems out of place on a page that is about Frequency Modulation. Maybe this was meant to say "a subtle amount of Frequency Modulation can simulate effects such as Vibrato"?

*  Some of the docs and comments seem to be out-of-sync with the actual code. For instance:
  
  ```js
  // multiply the modulator's output (amplitude ranges from -1 to 1) by 100, then add 200
  carrier.freq( modulator.mult(400).add(100) );
  ```

  The comment says we're multiplying by 100 and adding 200, but the code seems to say we're multiplying by 400 and adding 100?

  Also, I'm noticing that parts of the documentation, like the [`p5.Amplitude`](http://p5js.org/reference/#/p5.Amplitude) page, claim that "Amplitude measures volume between 0.0 and 1.0", yet other parts of the docs, like the code comment above, claim that it ranges from -1 to 1. I'm honestly not sure which one is right!

If others are likely to find this example as confusing as me, I'm interested in helping making it clearer, though I hope I wouldn't introduce any inaccuracies, as I don't know a lot about audio myself.

**Comment by lmccart** [comment]
great notes. I'm pinging @therewasaguy here because I also don't know that much about sound. :)
I do think the volume goes from 0 to 1, not -1.

@therewasaguy if you can provide clarification on some of the open questions here maybe @toolness could take a pass at cleaning up any inconsistencies in the docs and examples.

**Comment by therewasaguy** [comment]
Hi @toolness! Thanks for all your feedback on p5 sound examples. I will revise this example tonight, and i'll dig into some of the other github issues you've posted related to sound.

I'm glad you brought up how these conflicting uses of the term "amplitude" can be a source of confusion. p5.Amplitude takes a "buffer" (basically an array of ~ 1024 samples of time), and returns a single Root Mean Squared (RMS) value between 0 and 1. Each individual sample has an amplitude between -1 and 1, but with the RMS average, everything winds up being positive. RMS amplitude offers a better representation of how we perceive loudness or "amplitude."*

Let me know if this explanation is helpful, I will work on it more to incorporate it into the reference pages. There is definitely room to improve the learning resources for sound in general, so thanks for your help so far and please keep the feedback coming!

*Aside: ive thought about renaming the p5.Amplitude class to something like "Meter" or merging it with p5.FFT to make a single p5.Analyzer. I might make an issue to discuss this at the p5.sound repo in the long run. For now I'm inclined to keep it for parity with the Procrssing Sound library and existing examples.

**Comment by toolness** [comment]
Ah, thanks @therewasaguy, that explanation is indeed very helpful!

This is a bit of a digression, but is there any way to get the actual value of a signal for debugging purposes? For instance, in the FM example, I'd really like to "see" what `modulator.mult(400).add(100)` actually "looks" like, e.g. what it's minimum and maximum signal values are... It feels weird running just the modulator through a p5.Amplitude or p5.FFT because it's not really even audio, right? It's just a signal that's modulating the frequency of actual audio...

Oh, another thing I was confused about was the "order of operations" for `mult` and `add` on oscillators. It seems like it mimicks arithmetic order of operations by first multiplying and then adding, but I'm not sure. And it also seemed like `scale()` ought to ultimately do the same kind of thing as a combined `mult().add()` but when I tested this assumption by replacing a `mult().add()` with an equivalent `scale()`, it didn't sound the same at all.

Anyways, thanks for your help!

**Comment by therewasaguy** [comment]
@toolness curious if the [frequency modulation example](https://github.com/therewasaguy/p5.js-website/blob/p5sound/examples/examples_src/33_Sound/21_FreqModulation.js) makes more sense now. It might be too long.

As for the signal math, let's make a separate issue on p5.sound. I took that out of the examples for now, I'm not sure how many people are using it, and you can get pretty far by just changing the amplitude, like ``modulator.amp(100)`` which is the same thing as ``mult``. I agree with you that it's hard to picture what is happening, and if ``scale`` works properly we don't really need any others.

**Comment by toolness** [comment]
Yes, this is much better @therewasaguy!! Thanks! Will add notes to the new p5.sound issue you made.
