### ISSUE TITLE
missing a closing tag on reference pages

### ISSUE THREAD

**Issue by alisonag** [processing/p5.js-website#193]
There's a missing `</a>` closing tag that's causing a large portion of the reference page to be a clickable target for the copyright page. I'm constantly accidentally ending up on the copyright page when browsing the reference. It's most evident if you hover to the left or right of the main column on these pages.

You can find it here:
https://github.com/processing/p5.js-website/blob/master/reference/index.html#L115

It's also on all the reference subpages (modules, classes, files). For example: 
https://github.com/processing/p5.js-website/blob/master/reference/modules/Color.html#L115

**Comment by limzykenneth** [comment]
Looks like it affects a lot of pages. @lmccart Are the footers generated somehow? At the moment it seems to fix this someone will have to go through all of the affected pages and add the missing closing tags.

**Comment by lmccart** [comment]
yes, they're generated. the line to change is here:
https://github.com/processing/p5.js/blob/master/docs/yuidoc-p5-theme/layouts/main.handlebars#L115
and reinstructions to generate them are here:
https://github.com/processing/p5.js/wiki/Inline-documentation#generating-documentation

**Comment by limzykenneth** [comment]
Done~should work now : )

**Comment by alisonag** [comment]
amazing! Thanks for the quick response :smile:
