### ISSUE TITLE
frameRate() example throws a TypeError

### ISSUE THREAD

**Issue by toolness** [processing/p5.js-website#196]
The [`frameRate()` example](http://p5js.org/reference/#/p5/frameRate) is currently broken and `TypeError: a._renderer is undefined` is logged to the console.

The user sees a [screen](https://cloud.githubusercontent.com/assets/124687/11021981/b9f6998c-8620-11e5-9dda-c4b750815ebf.png) similar to the one shown in #188.

I'd like to fix this in two ways:

1. Fix the TypeError in the example code.
2. Make the example-runner a bit more fault tolerant, so that if examples fail, they don't make the reference page unreadable.

**Comment by lmccart** [comment]
:+1:
