### ISSUE TITLE
Styling issues for Examples 

### ISSUE THREAD

**Issue by ccanash** [processing/p5.js-website#198]
This issue will track the styling issues in the[ staging site](https://p5js-wip.online/examples/) for Examples page and subpages. Please add any additional items you might find during testing to this issue. 

**DESKTOP 1280 x 800**
- [x] Header:  Add padding below the title 
- [x] Content:The images are too wide in the previews. They should be less wide than the text.  

**TABLET 768 x 800**
Content:
- [x] There should be 2 elements per row. There are currently 4.
- [x] The images are too wide in the previews. They should be less wide than the text.  

**Mobile 428x800** 

- [x] #272
- [x] Header:The subtitle text in the header should be 20px and it is currently 32px. 

Content:
- [x] The featured section is missing
- [x] The images are too wide in the previews. They should be less wide than the text.  
In the detail page: https://p5js-wip.online/examples/animation-and-variables-drawing-lines/ 
- [x] The Title is not align with the rest of the text in the left margin

**Comment by davepagurek** [comment]
- [ ] Examples that load assets are not loading, e.g. https://p5js-wip.online/examples/imported-media-alpha-mask/
- [ ] Links to related examples broken, e.g. the links at the bottom of https://p5js-wip.online/examples/imported-media-alpha-mask/

**Comment by ccanash** [comment]
All items reported in my original comment have been addressed but I found a new issue:

- [ ] The image previews in the tablet resolution overlap with the H2 titles. 
![Screenshot 2024-04-25 at 14 58 56](https://github.com/processing/p5.js-website/assets/36164089/ebad83c8-c3c0-479a-be3d-d76121c59db8)
