### ISSUE TITLE
Add new primitive to example

### ISSUE THREAD

**Issue by hkirat** [processing/p5.js-website#200]
Need to edit [this](http://p5js.org/examples/examples/3D_Geometries.php) example so as to include the newly added primitive, ellipsoid.
Though the version of p5.js should be updated first.

**Comment by hkirat** [comment]
Ellipsoid was added to example but not to the library at p5js.org/js/p5.min.js.
Hence the reference http://p5js.org/reference/#/p5/ellipsoid is throwing an exception of ellipsoid not found.

**Comment by lmccart** [comment]
just updated the library, should be working now, thanks!
