### ISSUE TITLE
Some clean up on the references

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js-website#204]
Since I finally have some free time, I plan on doing some simple clean up on the docs. Mainly around consistencies like using "" instead of `` in some instances ([here](http://p5js.org/reference/#/p5/mouseClicked) and [here](http://p5js.org/reference/#/p5/keyPressed)) and adding some line breaks such as for the reference for [draw](http://p5js.org/reference/#/p5/draw). The last point may be only annoying me because I'm a graphic designer...  : P

**Comment by lmccart** [comment]
wonderful!
