### ISSUE TITLE
Examples for references of p5.image

### ISSUE THREAD

**Issue by PaliwalSparsh** [processing/p5.js-website#216]
There are no examples for many methods of p5.image. Can be seen on the Development Checklist for examples on https://github.com/processing/p5.js/wiki/Development---Checklist or on p5js.org references.

@lmccart I Sparsh Paliwal (as name was required :smile:) feel I can help with this issue, this is a followup on https://github.com/processing/p5.js/issues/249.

**Comment by lmccart** [comment]
wonderful! instructions for adding examples can be found here: https://github.com/processing/p5.js-website/wiki/Adding-examples. please let me know if you have any questions.

**Comment by PaliwalSparsh** [comment]
@lmccart as these are examples for reference I created another issue in the p5.js repo and have sent PR with required changes in inline documentation there. Please can you review them, I have done it for save(), copy() and filter() methods.
Corresponding issue in p5.js https://github.com/processing/p5.js/issues/1222.
