### ISSUE TITLE
Final people content needed

### ISSUE THREAD

**Issue by stalgiag** [processing/p5.js-website#219]
I just noticed that there is no content for people at the moment. There is only a placeholder example at the moment. Any idea when this content might be ready? @Qianqianye @limzykenneth @davepagurek 

We are moving quite fast this week so we have limited options. Unless the content is ready but not merged, I propose that we move forward with placeholder content, develop the layout, and hide the links for the people content for release.

**Comment by stalgiag** [comment]
I just realized that some of the content in the design seems like it could be copy-complete. Is this the case? Is there a sign-off on the images as well? If so I can author the MDX files.

**Comment by Qianqianye** [comment]
Hi @stalgiag, we will make a small adjustment on the design that we will have around 10 people in the list with all same image hierarchy. Each person will have name, profile pic, title, and a short bio. Could you make a template in the 'People' mdx file, so I can add the content by Tuesday?

**Comment by stalgiag** [comment]
[Example content is here](https://github.com/bocoup/p5.js-website/tree/main/src/content/people/en). The layout has already been coded so it should work as expected even after the final content is in without additional code updates.

**Comment by Qianqianye** [comment]
I will work on the people content today. In the 'About' page 'People' preview section, can we adjust the order of profiles?

**Comment by Qianqianye** [comment]
I have added some content for the people page in the PR #259.

We outlined the people page strucutre in this [doc](https://docs.google.com/document/d/1UwjWi2V4QSw0hT6MJfv4Zu00h58XP87gyPYcgGxO2CU/edit?usp=sharing), where we include 4 chapters: Project Leads, Project Mentors, p5.js Alumni, and p5.js contributor. We are planning to have same treatment for Project Leads, Project Mentors, p5.js Alumni, which means including same image size and bio. For the p5.js contributor, we are planning to get the name from the [Contributors](https://github.com/processing/p5.js?tab=readme-ov-file#contributors) session.

Please let us know if you have the capacity to implement this. Thanks!

cc @stalgiag @outofambit

**Comment by Qianqianye** [comment]
Hi just to follow up on this. We'd like to add the content if you could provide the page structure with chapters (Project Leads, Project Mentors, p5.js Alumni, and Contributors), we can add content from our side. 

@outofambit @stalgiag @ccanash

**Comment by outofambit** [comment]
@Qianqianye for now I think you can add everyone who is not a contributor as featured or alumni with the current schema. I can split featured into mentors and leads and adjust the styling. You would like the People page to have a header for each chapter and use the current styling for the leads for mentors, leads, and alumni within each of their respective chapters. Is that right?

**Comment by Qianqianye** [comment]
Yes, that's right. We also want to follow up with a previous comments in this thread that in the 'About' page 'People' preview section, the order of the profiles didn't follow the order in the 'People' page.

**Comment by outofambit** [comment]
@Qianqianye this is done and is currently deploying on `main`.

**Comment by Qianqianye** [comment]
Thanks @outofambit. I added the alumni info.  We will keep this issue open until we add the contributor list. Does the Bocoup team has the capacity to add the [Contributors](https://github.com/processing/p5.js?tab=readme-ov-file#contributors) list, as indicated in the final design?

**Comment by Qianqianye** [comment]
Thanks @outofambit. One last note about people content: The 'About' page' is currently showing all people content items (see screenshot below), and I believe we are only showing the first row according to the design. Is it something you can take a look? I can open an new issue if it's easier for organizational purpose.
<img width="1189" alt="image" src="https://github.com/processing/p5.js-website/assets/18587130/99ba7b15-ca4f-4c48-a843-bf71414bab5b">

**Comment by outofambit** [comment]
hi @Qianqianye, i didn't realize that 6 was a hard limit and not just the number of alumni + leads together available in the assumed content. i've limited it to 6 in 0e42fcc141e01600e2d4a613594500445a28f6f9.
