### ISSUE TITLE
Indicate loading of Reference section

### ISSUE THREAD

**Issue by iamjessklein** [processing/p5.js-website#229]
Sometimes it takes a while to load data and when you have a slow internet connection it can be challenging to tell if anything is happening on the page. This could easily be solved by providing the user some simple feedback with a throbber.

**Comment by lmccart** [comment]
great idea! i will work on this.

**Comment by lmccart** [comment]
added! it's just a basic throbber for starters. let me know if you have any feedback on look/design.

**Comment by toolness** [comment]
This looks great to me, thanks for adding it @lmccart !

(I'm not sure if you meant to re-open the issue? Or were you waiting for feedback from @iamjessklein before closing it?)
