### ISSUE TITLE
map. stop or stop2?  

### ISSUE THREAD

**Issue by tchoi8** [processing/p5.js-website#233]
Hi there

Just wondering if there's a technical reason for calling the upper bound of the value's target range
as stop, as opposed to stop2 
<img width="455" alt="screen shot 2016-03-19 at 3 21 09 pm" src="https://cloud.githubusercontent.com/assets/683107/13900849/3bdca63a-ede6-11e5-9d1a-777e8465023d.png">

In the documentation, it's written as stop2 as well. 

<img width="475" alt="screen shot 2016-03-19 at 3 19 54 pm" src="https://cloud.githubusercontent.com/assets/683107/13900892/5b64fda8-ede7-11e5-9f13-1c685a793f08.png">

I'm trying to make a cartoon tutorial for the map function, and it feels like stop2 will make it easier for the beginners to understand. 

![mapping](https://cloud.githubusercontent.com/assets/683107/13900886/356a026a-ede7-11e5-95b7-822a9999a1d8.jpg)
 

Thanks :)

**Comment by lmccart** [comment]
no reason, it should say stop 2. thanks :)
i'll make the change.

**Comment by tchoi8** [comment]
awesome.
