### ISSUE TITLE
CDN link on get-started page should auto-select on click

### ISSUE THREAD

**Issue by toolness** [processing/p5.js-website#241]
One of the things I like about the [Google Fonts pages](https://www.google.com/fonts#UsePlace:use/Collection:Montserrat) are that code snippets like the following always auto-select when you click on them:

> ![google-font-link](https://cloud.githubusercontent.com/assets/124687/14397136/bcd9545e-fda9-11e5-9bf3-62bda83d7803.png)

This makes it really easy to just copy the code to your clipboard and paste it into your editor.

It might just be because I come from a traditional web development background and don't use the p5 IDE, but I constantly find myself wishing the CDN link on the "Get Started" page worked the same way:

> ![cdn-link](https://cloud.githubusercontent.com/assets/124687/14397154/cd7b5a0a-fda9-11e5-9226-5e8c0ae23b75.png)

If this sounds like a good idea I'm happy to issue a PR.

**Side note:** Even cooler would be to have a little "copy to clipboard" button, but AFAIK such widgets need to Flash-based because web pages don't traditionally have access to the clipboard, so that's probably too much work and it wouldn't even work on devices that don't have Flash.

**Comment by toolness** [comment]
Update on the clipboard situation: apparently things have changed a bit and there is a [`ClipboardEvent` API](http://caniuse.com/#feat=clipboard) that is supported to varying extents on different browsers. Hmm.

**Comment by lmccart** [comment]
love the idea. i wonder if there's also something we could do with the reference example snippets. as it is right now, if you want to copy the code, you first have to click "edit" and then select and copy from the textarea. it'd be nice to make these easier to grab since i'd imagine people want to do this quite often.

**Comment by toolness** [comment]
Ah, good idea! I'll hack on something portable that can be used in both scenarios.

**Comment by toolness** [comment]
> i wonder if there's also something we could do with the reference example snippets. as it is right now, if you want to copy the code, you first have to click "edit" and then select and copy from the textarea. it'd be nice to make these easier to grab since i'd imagine people want to do this quite often.

I think I just fixed this in #255! :smile:

**Comment by lmccart** [comment]
indeed :)
