### ISSUE TITLE
Need Content for Privacy Policy and Terms of Use pages

### ISSUE THREAD

**Issue by outofambit** [processing/p5.js-website#242]
Just a heads up that the following pages need text. I wasn't able to find something in previous sites or repos to fill in for these.

- [Privacy Policy](https://p5js-wip.online/privacy-policy/)
- [Terms of Use](https://p5js-wip.online/terms-of-use/)

I also wrote something very simple for the [contact page](https://p5js-wip.online/contact), which might need to be revised.

cc @Qianqianye

**Comment by Qianqianye** [comment]
Hi, here is the [Privacy Policy](https://editor.p5js.org/privacy-policy) and [Terms of Use](https://editor.p5js.org/terms-of-use). Feel free to add them directly.

**Comment by outofambit** [comment]
Thank you @Qianqianye! I will port this content tomorrow.
