### ISSUE TITLE
sort() function  example not working 

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-website#244]
The example for the sort() function, mentioned in the p5.js website ( http://p5js.org/reference/#/p5/sort)
is not showing the result as mentioned in the code comment, line number 7  like (   print(words); // ["apple", "banana", "lime", "pear"]   )  same for the second example  line number 7 (  print(numbers); // [1,2,5,6,14,9,8,12]  )

**Comment by limzykenneth** [comment]
@kusha-b-k Did you mean the result is not showing up in the console? The particular examples on that page is set intentionally not to render, and hence not run, since without opening the console a user would not see any feedback on the canvas anyway.

**Comment by kusha-b-k** [comment]
I am not talking about  canvas , i am talking about console ... the result  as mentioned in the comment is not printing the exact result,, instead of that its  printing different value.. please check the below image...
![sort](https://cloud.githubusercontent.com/assets/14980964/14585087/8a92e988-0484-11e6-8c7a-5ceceff24ed1.png)

**Comment by kusha-b-k** [comment]
please check the below one also 
![so](https://cloud.githubusercontent.com/assets/14980964/14585101/20e2d2b8-0485-11e6-8b9c-515dc23fa623.png)

**Comment by limzykenneth** [comment]
Right! The example is wrong as the sort function does not alter the array passed in, instead it returns a sorted new array. I'll correct it today. Thanks!
