### ISSUE TITLE
save canvas image on specific folder in my server

### ISSUE THREAD

**Issue by Dazzid** [processing/p5.js-website#245]
HI,
I'm wondering what is the best way to save canvas image on specific folder in my server. 
I've been playing with  save(canvas, 'poster.png'); but it goes into download directly not into a folder on my server, how can I do this?
Thanks a lot for the help
David

**Comment by lmccart** [comment]
This is sort of beyond the scope of p5.js, which is a client-side only library. Basically, you'll need to run some server side code to handle this.. you can send the canvas data as a blob string via HTTP request and have your server code receive the request and save it out to a specific directory there.
