### ISSUE TITLE
code result  misposition

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-website#246]
please check the link   ( ** http://p5js.org/reference/#/p5/selectAll ** )  ,, the bug is red marked in the below image ... 
![bug](https://cloud.githubusercontent.com/assets/14980964/14761679/9447eb7a-0986-11e6-8238-e8d6743c7ace.png)

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/pull/1374
