### ISSUE TITLE
blend() documentation example not shown on website reference

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js-website#247]
Looks like there's no example in the website reference: http://p5js.org/reference/#p5.Image/blend

But the global function alias has an example here: https://github.com/processing/p5.js/blob/master/src/image/p5.Image.js#L515

**Comment by lmccart** [comment]
looks like there's an example [here](http://localhost/p5js.org/reference/#p5/blend) for the global method, but no example for the p5.Image method [here](http://p5js.org/reference/#p5.Image/blend). will add now..

**Comment by lmccart** [comment]
oh, maybe that's what you were saying in your initial comment, sorry. anyway, will fix. :)

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/commit/6eaa75c90e780c4c03d6bd11822b8a1e43f42cd5
