### ISSUE TITLE
Reference table of contents missing "Input (Time & Date)" heading link

### ISSUE THREAD

**Issue by akinhwan** [processing/p5.js-website#248]
![6223167989743616](https://cloud.githubusercontent.com/assets/10124722/14790354/e6b7f1d0-0ade-11e6-9151-78fc91fbc6b1.png)

The above image shows the "table of contents" at the top of the reference page, but does not include the "Input" heading. Which would make the number of links 16 instead of 15

![4905288681914368](https://cloud.githubusercontent.com/assets/10124722/14790385/0d28355a-0adf-11e6-83eb-8aac1524d422.png)

Very minor issue, just something I noticed. Also a first time "contributor", hope to find some real issues in the future :)

**Comment by lmccart** [comment]
thanks! this should actually be under the heading IO. I just made the change, should be fixed next time I update the docs on the site. https://github.com/processing/p5.js/commit/f780f620b3abc2c44e291f3791312e739316d832
