### ISSUE TITLE
Persistent problems with p5 Editor NOT saving 

### ISSUE THREAD

**Issue by danieldean1** [processing/p5.js-website#249]
I taught a workshop to students wherein the p5 Editor would not save or instantiate code changes in ongoing work resulting in confounding troubleshooting (and lame workaround =  copy+paste into another editor, quit p5, reopen, paste+save). 

Anyone else experiencing this?
I'm on v. 0.5.7, students are on latest build - happened in both versions.

**Comment by chiunhau** [comment]
Hi @danieldean1 
I think it's better to report this issue to p5.js-editor 😃 
https://github.com/processing/p5.js-editor/issues
