### ISSUE TITLE
Submitting SmokeParticleSystem example

### ISSUE THREAD

**Issue by sortofsleepy** [processing/p5.js-website#250]
👋  

Just wanted to submit a port of the Smoke Particles example from Processing. I couldn't find any mention of it in the issues so I assume no one else has done it?

Pull request to follow!

**Comment by lmccart** [comment]
great, go for it! instructions here: https://github.com/processing/p5.js-website/wiki/Adding-examples

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js-website/pull/251
