### ISSUE TITLE
website is crashing

### ISSUE THREAD

**Issue by lowenf** [processing/p5.js-website#254]
I tried to load http://p5js.org/reference/#/p5/ellipsoid but it kept crashing (firefox and chrome). Than for some magical reason it loaded in Chrome and I saw this:

![screen-shot-2016-05-29-at-16 22 23](https://cloud.githubusercontent.com/assets/4084169/15633993/e2e419b2-25b9-11e6-8dd6-fb35bed9e9c2.jpg)

My guess is there's some (p5) example that crashes the browser?

**Comment by limzykenneth** [comment]
Something is causing "inconsolata.woff" to load really slowly, no idea why.
![screen shot 2016-05-29 at 4 26 19 pm](https://cloud.githubusercontent.com/assets/7543950/15634377/31ffe30a-25ba-11e6-9441-6038716a3f41.png)

**Comment by limzykenneth** [comment]
Just fixed, not related to inconsolata, just some typo in the library.
