### ISSUE TITLE
Error with basicMaterial is not defined in example

### ISSUE THREAD

**Issue by nkolban** [processing/p5.js-website#256]
When visitin the "Materials" example found here:
https://p5js.org/examples/examples/3D_Materials.php
The latest Chrome logs the following error:

```
Uncaught ReferenceError: basicMaterial is not defined
draw @ VM451:29
d.redraw @ p5.min.js:7
(anonymous function) @ p5.min.js:5
(anonymous function) @ p5.min.js:5
e @ p5.min.js:5
(anonymous function) @ VM451:60
loadExample @ examples.js:137
(anonymous function) @ examples.js:28
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
```

**Comment by limzykenneth** [comment]
basicMaterial might have been removed because of it's similarity to normalMaterial I'm not sure, but at least basicMaterial is no longer in the docs and not in the source as well. Example probably needs update.

**Comment by indefinit** [comment]
Hi guys,

basicMaterial was intentionally removed because it mapped to fill() which was confusing.  If you want to fill a geometry with a color, please use fill() or ambientMaterial, if you want to blend with lights.
