### ISSUE TITLE
The reference of class() and id() in the p5.dom library should specify that they work as "getters" if no argument is given

### ISSUE THREAD

**Issue by sejomagno** [processing/p5.js-website#264]
I noticed that in the reference for other functions like  `html()`, `value()`, `position()`, `style()` and `attribute()` this behavior is described. As that was not the case for the `class()` and `id()` functions, I had to test them to make sure they worked in the same way.

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js/commit/bfda023839fe25d8f6058cb32597612d43d37a4e
