### ISSUE TITLE
p5.RendererGL  reference page error !

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-website#266]
alignment error  in the below link 
https://p5js.org/reference/#/p5.RendererGL/fill

![p5_jswebsiteerror](https://cloud.githubusercontent.com/assets/14980964/17363994/429d1830-599b-11e6-8966-bb9d605aa528.png)

**Comment by limzykenneth** [comment]
Probably related to [#1544](https://github.com/processing/p5.js/issues/1544)

**Comment by lmccart** [comment]
thanks, this has been fixed with the latest update to the library.
