### ISSUE TITLE
Live from Ada Lovelace Girls Who Code:  mispelling of "Daniel Shiffman"

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-website#268]
Hi,

I'm demonstrating how to file a github issue for Ada Lovelace Girls Who Code session at Goldman Sachs. When looking at the sine wave example on p5js.org, we noticed Daniel Shiffman is spelled "Danial Shiffman."

I'll make a pull request to fix this soon!

Dan and everyone at Ada Lovelace Girls Who Code session at Goldman Sachs :D

**Comment by lmccart** [comment]
fixed with https://github.com/processing/p5.js-website/pull/269
