### ISSUE TITLE
Accessibility, Performance and Maintainability

### ISSUE THREAD

**Issue by nok** [processing/p5.js-website#272]
Hello all,

I want to contribute in some fixes and improvements. The main goal is to improve the accessibility and performance in general. Furthermore I want to improve the code quality and make it easier to maintain. The following list shows the summarized tasks:

**Small issues**:
- Fix: onResize() doesn't work from the iframe embedded sketch (https://github.com/processing/p5.js-website/pull/273)
- Fix: change the numbers of polygons to improve the FPS on high resolution screens (https://github.com/processing/p5.js-website/pull/273)

**Medium issues**:
- Improve the accessibility and semantic of the DOM
  - Move the foundation bar to the bottom (in DOM) for better keyboard navigation
  - Add semantic HTML elements [[1]] for SEO and screen reader readability
  - Add aria attributes [[2]] [[3]] for better screen reader readability
  - Add `tab-index` attributes [[4]] where it's necessary to improve the navigation
  - Add noticeable outline style for focused elements [[5]] ;-)
- Clean up the file structure (don't mix assets/resources with content pages), e.g.:
  - Move `css`, `js`, `img` to `assets` dictionary
  - Remove `test` and `p5-tests` with old or useless content

**Large issues**:
- Setup build process based on [Gulp](https://github.com/gulpjs/gulp) or [Grunt](http://gruntjs.com/) to optimize the page speed and performance:
  - Clean, uglify and merge CSS files
  - Merge JS files
  - Optimize images
- Add modular downloader [[6]]
- Add test automation to detect 404, 500 links

So what do you think?

Happy coding,
Darius

[1]: https://www.w3.org/WAI/PF/aria/
[2]: https://www.w3.org/WAI/PF/aria/
[3]: https://www.w3.org/TR/html-aria/
[4]: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
[5]: http://www.outlinenone.com/
[6]: https://github.com/processing/p5.js/issues/94

**Comment by CleezyITP** [comment]
Good timing @nok ! I'm working on the "Medium issues" (accessibility stuff) this and next week if you want to combine efforts.

**Comment by lmccart** [comment]
sounds great! however, we're about to launch a new website that supports internationalization...would you mind submitting the PR over there? https://github.com/mayaman/p5js-website

let me know if you have any questions with the setup and build process

**Comment by nok** [comment]
Yes, I will do that. Furthermore I will push some improvements.
Yesterday I forked the repo and added already [some changes](https://github.com/nok/p5js-website/commits/performance_optimizations).

**Comment by nok** [comment]
Update: https://github.com/mayaman/p5js-website/pull/9

**Comment by nok** [comment]
I close this issue, because the major points are implemented. :octocat:
