### ISSUE TITLE
On the reference page, p5.Image methods are duplicated

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#344]
On https://beta.p5js.org/reference/#Image, the first subsection (just labelled "Image") seems to have the same content as the last subsection (labelled "p5.Image".) This doesn't happen for every subsection from a class (e.g. p5.Geometry doesn't have this problem.)

I need to look into whether or not this is something we can fix in the UI or whether it requires a data change. Leaving this issue here so I don't forget about it.

**Comment by limzykenneth** [comment]
This is mainly because the one directly under Image is the functions that is called as is and act on the main canvas, whereas for those under p5.Image acts against p5.Image object instance (ie. `img.filter()`). I'm not sure a data change will make sense here and probably a UI change for object instance methods to make it clear what they are will work better.

**Comment by davepagurek** [comment]
Ah ok so the methods are all valid? They still link to the same URLs that include p5.Image, that's probably in need of fixing at least

**Comment by limzykenneth** [comment]
Yup, they are essentially [this page](https://p5js.org/reference/#/p5/filter) and [this page](https://p5js.org/reference/#/p5.Image/filter) respectively. The contents are very similar as well.

**Comment by davepagurek** [comment]
Wait, actually those do still exist [but in the `pixels` category a little below.](https://beta.p5js.org/reference/#Pixels) It looks like that first section really is just a duplicate?

**Comment by limzykenneth** [comment]
There's something not quite right going on here. `blend()` under `pixels` actually links to the constant `BLEND`.

**Comment by davepagurek** [comment]
There was some discussion before about the naming collision between constants and methods, what was the result of that? I wonder if that incorrect link could be related

**Comment by davepagurek** [comment]
I think I've got a fix, I'll put up a PR soon. Also just noticing that when a method has multiple overloads with shared parameter names, it duplicates the shared names but without a description:

![image](https://github.com/processing/p5.js-website/assets/5315059/2dccd54d-2e52-4e45-87b7-bc55a32974c8)

vs on the current site:

![image](https://github.com/processing/p5.js-website/assets/5315059/34e2d6ad-b82d-4359-9bf3-35dadd904a3c)

I'll address that too.
