### ISSUE TITLE
Translating the setup() function to Spanish

### ISSUE THREAD

**Issue by lauradowell** [processing/p5.js-website#356]
The setup() function documentation page on the p5.js beta website is currently not available in Spanish. This presents a barrier to Spanish-speaking users who rely on the translated documentation to effectively use p5.js. I can fix this. https://beta.p5js.org/es/reference/p5/setup/

**Comment by limzykenneth** [comment]
@Qianqianye I realised there are some things that are still not translated that we probably would want them to be like `setup()` mentioned here and `draw()`. Were they included in the previous batches or we didn't get around to it?

**Comment by Juan31416** [comment]
If you need any extra help @lauradowell. Please let me know.

**Comment by lauradowell** [comment]
Hi Juan, thank you. I didn't need help with these ones, but I think there are other issues on the website in Spanish that don't translate properly.

**Comment by Juan31416** [comment]
No problem, glad I could help! Thanks for letting me know about the other issues.

**Comment by limzykenneth** [comment]
@Juan31416 Would you be able to have a look at #388 to check the translation looks good overall? Thanks.

**Comment by Juan31416** [comment]
Hi @limzykenneth ,

Thanks for reaching out! I've been happy to look at the translation. 

I've reviewed the Spanish version and made suggestions to improve readability. The overall meaning is conveyed accurately, but minor tweaks could enhance clarity.

**Comment by lauradowell** [comment]
@Juan31416 Sounds good, those improvements sound great
