### ISSUE TITLE
Potential 1.9.4 release this week

### ISSUE THREAD

**Issue by Qianqianye** [processing/p5.js-website#359]
We updated more  reference last couple of weeks. We'd like to do a patch `1.9.4` release on this Tuesday or Wednesday, and we want to double check with you first to see if it's okay. Thanks!  @outofambit @stalgiag

CC @limzykenneth @davepagurek

**Comment by outofambit** [comment]
@Qianqianye yep, sounds good! The relevant steps to update the website after a p5 release are in https://github.com/processing/p5.js-website/blob/main/docs/scripts.md. I will add a few more details to that page shortly if someone else would like to give it a try this time?

**Comment by limzykenneth** [comment]
I had a look at the possible steps for release here and there are two things that need to be hooked up, both relating to version numbers.

We want version numbers on website for anywhere that references it and relevant CDN script tags to be updated to the latest when there is a release. The first place is in the "Download" page where I see that the number is currently hard coded in. The second in for the embeds which is used by CDN links is defined as a global value which is also hardcoded and it is in TS so would be trickier to script an automated number update, as oppose to having a JSON file that can be easily parsed and updated.

The YUIDoc JSON file should have a version number in there already but it is a bit more about simple build still having the version number without having to fetch the library website for it (or anything online really).
