### ISSUE TITLE
Alt text not showing on Example page thumbnails

### ISSUE THREAD

**Issue by Qianqianye** [processing/p5.js-website#380]
Alt text is not showing on most Example page thumbnails when 'View Alt Text' is checked. See screenshot below:

CC @outofambit @davepagurek @limzykenneth @ccanash

![image](https://github.com/processing/p5.js-website/assets/18587130/ab15ad48-bee8-4dae-9105-3d207f84273d)

**Comment by davepagurek** [comment]
I think this one is a content issue. e.g. Shape Primitives has an alt:

https://github.com/processing/p5.js-website/blob/b931f577e3a0079a608520be75581b531590e82c/src/content/examples/en/01_Shapes_And_Color/00_Shape_Primitives/description.mdx?plain=1#L2-L4

...but Mobile Device Movement doesn't:

https://github.com/processing/p5.js-website/blob/b931f577e3a0079a608520be75581b531590e82c/src/content/examples/en/02_Animation_And_Variables/02_Mobile_Device_Movement/description.mdx?plain=1#L2-L3

...so we'll probably have to go through them all and write some descriptions.

**Comment by Qianqianye** [comment]
Thanks @davepagurek! Hi @calebfoss, could you double check if all example thumbnails include alt text? Thanks!

**Comment by davepagurek** [comment]
Just took a quick scan through https://github.com/processing/p5.js-example and it looks like there wasn't alt text metadata there and the examples that currently have alt text were added by @outofambit in https://github.com/processing/p5.js-website/pull/189, so I thiiink we'll probably have to create those fresh

**Comment by calebfoss** [comment]
@davepagurek Yes, that's correct. Alt text for thumbnails was not part of that project. I'd be happy to help out with that though.

**Comment by calebfoss** [comment]
We did add canvas descriptions to the code for each example, so the text in those would be a good starting point.

**Comment by calliecramer** [comment]
Hey, happy to help out with this!

**Comment by Qianqianye** [comment]
Closing this issue since it's resolved in PR #529
