### ISSUE TITLE
Link to not active development libraries from oficial website, is it a good idea?

### ISSUE THREAD

**Issue by v-k-** [processing/p5.js-website#389]
Not sure if this is the right place to post. 
I just went to the site to check if are there libraries for using maps tiles with p5.js. I found [mappa](https://github.com/cvalenzuela/Mappa). But looks like it is not active in development (6year last commit). Some of the examples don't load and issues are not responded. So I'm just wondering if it is a good idea to have it linked from the site.
Thanks.
cheers.

**Comment by Qianqianye** [comment]
Thanks @v-k- for bringing up this issue. The creator of [mappa](https://github.com/cvalenzuela/Mappa) didn't respond to our recently open call for libraries, so the [mappa](https://github.com/cvalenzuela/Mappa) libraries is  currently not included in the new website (https://beta.p5js.org/libraries/), which will be launched soon.
