### ISSUE TITLE
Underline on reference link breaks on the brackets

### ISSUE THREAD

**Issue by Qianqianye** [processing/p5.js-website#391]
When being hovered, the underline on reference link breaks on the brackets part. See screenshot, eg. arc() below.

cc @outofambit @davepagurek @limzykenneth @ccanash

<img width="481" alt="image" src="https://github.com/processing/p5.js-website/assets/18587130/5247cb0e-c5e0-4226-a3f1-c56ade8ce39d">

**Comment by Qianqianye** [comment]
Thanks @davepagurek. Tagging the designers @stefanietam @tyler-yin to take a look at this issue, since I wasn't able to find the hover state of the reference page in the design.

I think we can adjust the hover state style because the in current p5.js website reference page, the hovered links won't skip brackets (see screenshot below).
![image](https://github.com/processing/p5.js-website/assets/18587130/9ef158bd-b3c3-45f4-825e-3cf892fea07b)

**Comment by tyler-yin** [comment]
Hi,

Would it be possible to slightly adjust the `text-underline-offset` property until the underline no longer breaks?
https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset

Thanks!

**Comment by Qianqianye** [comment]
Thanks @tyler-yin. To keep link style consistent across the website, do you have a recommended offset value in this case?

**Comment by tyler-yin** [comment]
For text that uses Courier, we recommend `text-underline-offset: 15%`

For text that uses National Park we recommend `text-underline-offset: 10%` 

However, for National Park, please keep in mind that with this offset value, the descenders will still break the underline. Unfortunately, there isn't really an ideal offset value that will keep the underline unseparated.

Ultimately, we are also fine with the underline being kept as is!

**Comment by limzykenneth** [comment]
In that case I think we'll keep it. I personally think it adds some character anyway. @Qianqianye @davepagurek What do you think?

**Comment by davepagurek** [comment]
sounds good to me!
