### ISSUE TITLE
Jump to links spacing

### ISSUE THREAD

**Issue by limzykenneth** [processing/p5.js-website#416]
I just noticed that on some pages the jump to links on the sidebar have extra spacing to differentiate between items while some did not. See screenshots below for the Examples page and Tutorials page, with the Examples page not having that spacing making it hard to differentiate where one item only take up one line or two lines:

![Screenshot 2024-06-19 at 21-04-16 Examples](https://github.com/processing/p5.js-website/assets/7543950/a7dbf364-1d3c-4542-a5a2-f38a324132e7)

![Screenshot 2024-06-19 at 21-04-38 Tutorials](https://github.com/processing/p5.js-website/assets/7543950/bc71946c-614b-4c62-9e0f-74640efd9d71)

I found at [these lines](https://github.com/processing/p5.js-website/commit/45ac22a49b65715194ccd18ecc53f516a0575ec4#diff-8923bf1f2130a7a2f2b2906a02a8fd3965f841fefbdf527752b9135d1a81802dR281-R287) it seems the spacing is only applying to the contribute, tutorials, and about page. @outofambit @stalgiag Is there some reason why the spacing is only applied to these select pages instead of applying to all pages with jump to links?

**Comment by outofambit** [comment]
Hi @limzykenneth! Yes, this was part of the designs I was working from. I'm not sure about the rationale for having the spacing be different between these pages. The wider spacing does make differentiating items easier for me too personally. 

@tyler-yin curious if you have any thoughts! 🙏🏽

**Comment by tyler-yin** [comment]
Hi @limzykenneth @outofambit 

Thanks for bringing this up. The rationale for the extra spacing between links in pages like "Tutorials" was to differentiate each link for pages where the text would likely overflow, which we initially saw applied to just some of the pages. However, for consistency across the site, I think it makes sense to move forward with this spacing for all pages.
