### ISSUE TITLE
Some images are overflowing on mobile

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#429]
e.g. this one on the STF event page:

![Screenshot_20240701-105611.png](https://github.com/processing/p5.js-website/assets/5315059/e43b47d1-fe49-4454-88ca-caed7840e604)

Possibly responsible for this behaviour? https://x.com/jcubic/status/1807782477701714286?t=NSeO9NbrV0tEMEgqmnLA-w&s=19

**Comment by Qianqianye** [comment]
Hi @outofambit and @stalgiag, do you might know how to fix this issue? thanks!
