### ISSUE TITLE
Examples have play/stop buttons cut off

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#433]
<img width="1149" alt="image" src="https://github.com/processing/p5.js-website/assets/5315059/d23b6f0e-bc06-493f-87b3-e91af2b4a0f8">

I think my update to size community sketches to fit the window may have broken this?

**Comment by Qianqianye** [comment]
Thanks @davepagurek. Tagging @outofambit @stalgiag as they might be able to offer insights.

**Comment by wagedu** [comment]
Not sure if it's related but some of the Reference examples are auto-run while others need the Play button to be pressed.
ie:
https://p5js.org/reference/p5/arc/
3 first examples auto-run, next 7 don't

https://p5js.org/reference/p5/ellipse/
4 first examples auto-run, the 5th don't

**Comment by davepagurek** [comment]
Separate issue I think, I'll make a new issue for this
