### ISSUE TITLE
Some example metadata is sneaking into rendered code in the reference

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#436]
e.g. on https://p5js.org/reference/p5/windowResized/ the `<div class="norender">` is visible in the code, causing it to not run:

![image](https://github.com/processing/p5.js-website/assets/5315059/9114af53-698a-4149-b448-b58f55987961)

**Comment by davepagurek** [comment]
Another example, `<div modernizr="webgl">` is showing up here: https://p5js.org/reference/p5/loadShader/

**Comment by shiffman** [comment]
Also here! https://p5js.org/reference/p5.Vector/dist/ (capturing this page for a video tutorial!)

**Comment by davepagurek** [comment]
@shiffman that page should be fixed now, if you haven't already finished your video!

**Comment by shiffman** [comment]
Yay thank you @davepagurek, the fixed page made it in! https://youtu.be/dJNFPv9Mj-Y
