### ISSUE TITLE
Some reference examples don't immediately show up, need to click the play button

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#442]
@wagedu mentioned this in a prior comment:

> Not sure if it's related but some of the Reference examples are auto-run while others need the Play button to be pressed.
> ie:
> https://p5js.org/reference/p5/arc/
> 3 first examples auto-run, next 7 don't
> 
> https://p5js.org/reference/p5/ellipse/
> 4 first examples auto-run, the 5th don't

Seems that the culprit is the `lazyLoad` property on the `CodeEmbed` widget: https://github.com/processing/p5.js-website/blob/974470a0c2e89f5c50e2cf9d243f47cf12a63179/src/layouts/ReferenceItemLayout.astro#L105

[This hands things off to the browser](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/loading) and it seems like the browser isn't correctly loading them when they become visible.

It could be ok if `CodeEmbed` is always eager because they already don't immediately start running until they scroll into view (we have scroll detection and an `IntersectionObserver1 for this.) So maybe it's worth just relying on that?

**Comment by Qianqianye** [comment]
Thanks @davepagurek. Wondering if @outofambit @stalgiag have any insights on this?

**Comment by stalgiag** [comment]
> It could be ok if `CodeEmbed` is always eager because they already don't immediately start running until they scroll into view (we have scroll detection and an `IntersectionObserver1 for this.) So maybe it's worth just relying on that?

I agree with this. Thanks @davepagurek
