### ISSUE TITLE
Reintroduce GitHub file links on Reference pages

### ISSUE THREAD

**Issue by meezwhite** [processing/p5.js-website#456]
### Increasing Access

Unsure

### Most appropriate sub-area of p5.js?

Reference

### Feature request details

On the old reference site, we used to have the following portion at the end of each reference page:

Example from the old [color() reference page](https://archive.p5js.org/reference/#/p5/color):

> Notice any errors or typos? [Please let us know.](https://github.com/processing/p5.js/issues) Please feel free to edit [src/color/creating_reading.js](https://github.com/processing/p5.js/blob/v1.9.4/src/color/creating_reading.js#L398) and issue a pull request!

I often found this section incredibly useful, especially when I was looking up the implementation details of specific functions. However, in the new reference pages, this linking to the respective GitHub files is missing, which makes it challenging to find the exact function I’m looking for.

Would it be possible to reintroduce these links on the new reference pages as well? This would greatly enhance the usability of the reference documentation by providing quick and direct access to the implementation details and encouraging contributions.

**Comment by Qianqianye** [comment]
Thanks @meezwhite for the suggestion. The feature is added in PR #466.
