### ISSUE TITLE
External link for Cassie Tarakajian takes you to the wrong website. 

### ISSUE THREAD

**Issue by pluto-bell** [processing/p5.js-website#480]
### Most appropriate sections of the p5.js website?

About

### What is your operating system?

Mac OS

### Web browser and version

Version 126.0.6478.183 (Official Build) (arm64)

### Actual Behavior

Under the "People" section, clicking on "Cassie Tarakajian" takes you to Kenneth Lim;s website instead.

### Expected Behavior

To be taken to Cassie Tarakajian's website.

### Steps to reproduce

- Go to: [https://p5js.org/about/](url)
- Scroll down to the "People" section and locate Cassie Tarakajian.
- Click on Cassie's name

<details>
<summary>Use video capture for reference</summary>

https://github.com/user-attachments/assets/5a40f8b3-432a-4b8a-a578-c5bfab9a2058

</details>

### Would you like to work on the issue?

Yes, I can complete this issue.

**Comment by pluto-bell** [comment]
Found PR #478 that takes care of issue.

**Comment by davepagurek** [comment]
Closed by https://github.com/processing/p5.js-website/pull/478 now!
