### ISSUE TITLE
Foundation category displays duplicate entries for `Number` and `Object`

### ISSUE THREAD

**Issue by meezwhite** [processing/p5.js-website#484]
### Most appropriate sections of the p5.js website?

Reference

### Actual Behavior

Duplicate entries for `Number` and `Object` under Foundation category are displayed:

![p5js_issue_484](https://github.com/user-attachments/assets/f950a3eb-cfa7-4bcc-aba6-981ff084e88f)

For `Number` one entry links to https://p5js.org/reference/p5/number (first letter lowercase) and the other links to https://p5js.org/reference/p5/Number (first letter uppercase).

For `Object` one entry links to https://p5js.org/reference/p5/object (first letter lowercase) and the other links to https://p5js.org/reference/p5/Object (first letter uppercase).

### Expected Behavior

For `Number` I'd expect only the entry with the link to https://p5js.org/reference/p5/Number (first letter uppercase) to be displayed.

For `Object` I'd expect only the entry with the link to https://p5js.org/reference/p5/Object (first letter uppercase) to be displayed.

### Steps to reproduce

1. Navigate to https://p5js.org/reference
2. In the left navigation, Jump to: Foundation

Notice duplicate entries for `Number` and `Object`

### Would you like to work on the issue?

Yes

**Comment by limzykenneth** [comment]
This should be fixed by https://github.com/processing/p5.js-website/commit/6e9a25fb47aa90c6a89c3306279009292bba77ae
