### ISSUE TITLE
404 error when looking up references for WEBGL, WEBGL2

### ISSUE THREAD

**Issue by GenericMale1** [processing/p5.js-website#485]
### Most appropriate sections of the p5.js website?

Other (specify if possible)

### What is your operating system?

Mac OS

### Web browser and version

Safari Version 17.6 (19618.3.11.11.5)

### Actual Behavior

when you use the search function to look up references or go through the reference list for either of the two, and on links to examples, you reach a 404 page.

https://github.com/user-attachments/assets/8eb3fed4-eaba-4bae-82a5-10fab8aeb93b

### Expected Behavior

well, the reference page

### Would you like to work on the issue?

no

**Comment by mayaarguelles** [comment]
Hi, would it be alright to work on this? I think I see what's causing this, which is the logic that removes 'constants/' or 'types/' from the path that gets applied [in the router](https://github.com/processing/p5.js-website/blob/15ff0b20d7257c95fc90aa6e274e215f72ae17b1/src/pages/_utils.ts#L155) not getting applied in the search indices build script.

**Comment by stalgiag** [comment]
> Hi, would it be alright to work on this? I think I see what's causing this, which is the logic that removes 'constants/' or 'types/' from the path that gets applied [in the router](https://github.com/processing/p5.js-website/blob/15ff0b20d7257c95fc90aa6e274e215f72ae17b1/src/pages/_utils.ts#L155) not getting applied in the search indices build script.

@mayaarguelles yep that's probably the culprit. You are definitely welcome to take it on! Let me know if you need any help.

**Comment by GenericMale1** [comment]
heyhey, turns out the issue persists with the old version of the website as well, I am so confused as to what is going on?
