### ISSUE TITLE
404 error while searching for content related to contributing

### ISSUE THREAD

**Issue by mayaarguelles** [processing/p5.js-website#495]
### Most appropriate sections of the p5.js website?

Contribute

### What is your operating system?

Mac OS

### Web browser and version

Google Chrome 127.0.6533.100, Safari 16.6

### Actual Behavior

Searching for content related to contributing leads to 404 pages for a couple of pages with paths transformed from their original source files. For example, searching for "contributing" leads to incorrect links for the readme (links to [/contribute/README/](https://p5js.org/contribute/README) rather than [/contribute/readme/](https://p5js.org/contribute/readme/)) and contributing to the p5.js reference (links to [/contribute/contributing_to_the_p5.js_reference](https://p5js.org/contribute/contributing_to_the_p5.js_reference) rather than [/contribute/contributing_to_the_p5js_reference/](https://p5js.org/contribute/contributing_to_the_p5js_reference/)) sections in the results.

https://github.com/user-attachments/assets/93bbdfe8-a6d3-4a87-ab39-53498b0b39c6

### Expected Behavior

To be able to reach the appropriate pages

### Steps to reproduce

1. Search for "contributing" in the top nav.
2. Click on the entries for "🌸 Welcome! 🌺" or "Contributing to the p5.js Reference".

### Would you like to work on the issue?

Yes, I'd like to work on this

**Comment by thegodworm** [comment]
![afbeelding](https://github.com/user-attachments/assets/ed8de06c-6007-4f18-9b98-4e7b9d582226)
https://p5js.org/contribute/contributor_guidelines.md#software-design-principles

Yes, it's also a problem for me

**Comment by limzykenneth** [comment]
Please direct all 404/deadlink related reports to #527 and we'll resolve them there. I'll close this for organizational purposes as the reported link are covered in #527. Thanks.
