### ISSUE TITLE
/contribute/access/ needs another line break/margin before heading "Kinds of access"

### ISSUE THREAD

**Issue by AaratiAkkapeddi** [processing/p5.js-website#498]
### Most appropriate sections of the p5.js website?

Contribute

### What is your operating system?

Mac OS

### Web browser and version

Firefox 129.0.2

### Actual Behavior

![Screenshot 2024-08-27 at 4 56 07 PM](https://github.com/user-attachments/assets/ebc34967-dbfc-4d99-a523-f6bdab050fa6)

There is no line break above "Kinds of Access" (on both desktop and mobile)

### Expected Behavior

I believe there should be a line break above "Kinds of Access"
Right now, there is a margin-bottom of `var(--gutter-md)`
So instead it could be a margin-_top_ of `var(--gutter-md)` like this:

![Screenshot 2024-08-28 at 9 34 30 AM](https://github.com/user-attachments/assets/3bd5553d-57ac-48ad-9973-4fe558d29ca8)

### Steps to reproduce

Navigate to https://p5js.org/contribute/access/

### Would you like to work on the issue?

Yes

**Comment by 7malikk** [comment]
Hi @Qianqianye,

I noticed this issue has been resolved [here ](https://github.com/processing/p5.js-website/pull/506) thanks to @shourysingh07 

I believe we can close this as done, great spot @AaratiAkkapeddi by the way.

**Comment by shourysingh07** [comment]
Yes, the issue has been resolved and can now be closed.
