### ISSUE TITLE
Broken Link To Next Step In src/content/tutorials/en/variables-and-change.mdx

### ISSUE THREAD

**Issue by valkyriedimension** [processing/p5.js-website#502]
### Most appropriate sections of the p5.js website?

Tutorials

### What is your operating system?

Windows

### Web browser and version

Firefox 129.0.2, Chrome 128.0.6613.114

### Actual Behavior

Opening the "Next Step" link within the [Variables and Change](https://p5js.org/tutorials/variables-and-change/) tutorial opens [this webpage and reports a 404.](https://p5js.org/tutorials/conditions-and-interactivity/)
![image](https://github.com/user-attachments/assets/9359ed67-6504-4116-94fb-aca38b8559da)

### Expected Behavior

(I think) the link should direct to the [Conditionals and Interactivity](https://p5js.org/tutorials/conditionals-and-interactivity/) portion of the tutorial.

### Steps to reproduce

* Visit https://p5js.org/tutorials/variables-and-change/
* Attempt to open the "Next Step" link at the end of the tutorial

### Would you like to work on the issue?

Yes

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Qianqianye** [comment]
Thanks @valkyriedimension. This issue is now fixed in #503.
You are now added in [p5.js contributor list](https://github.com/processing/p5.js?tab=readme-ov-file#contributors) 🎉.
