### ISSUE TITLE
Fix broken link on p5.js website page for "p5.js Web Accessibility"

### ISSUE THREAD

**Issue by iamniky** [processing/p5.js-website#511]
### Most appropriate sections of the p5.js website?

Home

### What is your operating system?

Windows

### Web browser and version

Firefox v130.0, though would affect all.

### Actual Behavior

When users visit the URL https://p5js.org/contribute/web_accessibility/ and click on the hyperlink that is labeled "Using p5.js with a Screen Reader tutorial", they are met with a 404 error page:

![Screenshot 2024-09-06 004138](https://github.com/user-attachments/assets/64d03f26-2e32-44e0-81ff-84f06d89485d)

![Screenshot 2024-09-06 004201](https://github.com/user-attachments/assets/0e1a7f1a-4b51-470e-a12d-9855ba72ef69)

### Expected Behavior

We expect that when the users click the hyperlink labeled "Using p5.js with a Screen Reader tutorial", they are taken to a page with information regarding a tutorial about using p5.js with a screen reader.

### Steps:

1. Go to https://p5js.org/contribute/web_accessibility/
2. Click on respective link (listed in table below).
3. Get a 404 error.

### Solution:

Replace listed broken links to the correct links.

Source link text: | Current link: | Suggested link:
-- | -- | --
Using p5.js with a Screen Reader tutorial | https://p5js.org/learn/p5-screen-reader.html | ???

### Would you like to work on the issue?

Yes, I'd like to work on the issue.

**Comment by shourysingh07** [comment]
I would like to work on this issue.

**Comment by Qianqianye** [comment]
Thanks @iamniky for reporting the bug. The link should go to https://p5js.org/tutorials/p5js-with-screen-reader/

Hi @shourysingh07, if you are interested in working on this, please go ahead and fix the link in [this line](https://github.com/processing/p5.js/blob/main/contributor_docs/web_accessibility.md?plain=1#L9) and open a PR within p5.js library repo. Thank you!

**Comment by shourysingh07** [comment]
Thank you @Qianqianye ! I've opened a pull request within the [p5.js library repo](https://github.com/processing/p5.js).

Here is the [PR Link](https://github.com/processing/p5.js/pull/7254).

**Comment by Qianqianye** [comment]
Closing this issue since it's fixed in PR [#7254](https://github.com/processing/p5.js/pull/7254) in p5.js repo.
