### ISSUE TITLE
Problem with html symbols at https://p5js.org/reference/#Foundation

### ISSUE THREAD

**Issue by goldwasser** [processing/p5.js-website#522]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Mac OS

### Web browser and version

128.0.6613.120 (Official Build) (x86_64) 

### Actual Behavior

For both the > and >= summary description as visible on https://p5js.org/reference/#Foundation errant symbols are being shown as seen in image below. 
<img width="303" alt="Screenshot 2024-09-07 at 9 51 55 AM" src="https://github.com/user-attachments/assets/3a8a4a4b-d930-4da5-851e-4297d7e496a1">

### Expected Behavior

If mirroring approach that seems to happen for < and <= the symbols can just be omitted so that summary reads "The greater than or equal to operator evaluates to true if ..."

### Would you like to work on the issue?

no

**Comment by meganmckissack** [comment]
I'd like to work on this, I found a few other related bugs in the same foundation section of the reference, all related to the page and url name changes from `<` type symbols characters like "lt".

**Comment by davepagurek** [comment]
I left some discussion on a related issue here https://github.com/processing/p5.js-website/issues/447#issuecomment-2239528853 about how to diagnose the source of the issues, so that you can target a fix in the right spot. Maybe take a look and see where the same reasoning leads you for this one.

**Comment by davepagurek** [comment]
Update on this: turns out those operator references don't even exist any more in the p5.js repo! I thought I was going crazy haha, but I think the problem is that when we build the reference, it just creates/modifies new files, but never deletes old ones if items are removed from the reference.
