### ISSUE TITLE
Incorrect rendering of html characters at https://p5js.org/examples/animation-and-variables-conditions/

### ISSUE THREAD

**Issue by goldwasser** [processing/p5.js-website#528]
### Most appropriate sections of the p5.js website?

Contribute

### What is your operating system?

Mac OS

### Actual Behavior

What should be rendered as the `&&` operator is being rendered as `&$amp;` at https://p5js.org/examples/animation-and-variables-conditions/
<img width="735" alt="Screenshot 2024-09-08 at 11 42 06 AM" src="https://github.com/user-attachments/assets/977b3e24-93b6-4d8e-8d7c-806b4f6ccfa7">

### Expected Behavior

Should be rendered as `&&`

### Would you like to work on the issue?

no

**Comment by xuv** [comment]
Happy to pick up this issue. I have also identified that the error exists also in the hindi and chinese translations as well.
