### ISSUE TITLE
"Duplicate content entry slug" error occurred with i18n in some pages.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-website#541]
### Most appropriate sections of the p5.js website?

Other (specify if possible)

### What is your operating system?

None

### Actual Behavior

I have attempted to internationalize some pages.
(In my case, I am working on translating the Japanese version.)

But "Duplicate content entry slug" error occurred when copy "en" folder to non-English lang folder (e.g. es) in pages follows:

/src/content/pages/
/src/content/tutorials/

### Expected Behavior

These pages also support internationalization.
(However, I cannot discern whether this is a bug or a policy that does not require internationalization.)

### Steps to reproduce

In your development environment.
e.g. Copy /src/content/pages/en to /src/content/pages/es
e.g. Copy /src/content/tutorials/en to /src/content/tutorials/es

### Would you like to work on the issue?

someone

**Comment by Nitin-Budakoti** [comment]
hey @shibomb 
can i work on this , i am  new to this community.

**Comment by shibomb** [comment]
> hey @shibomb can i work on this , i am new to this community.

Hi @Nitin-Budakoti 
After creating this Issue, I continued my research and found a solution, so I created a PR for it.
Thank you for your interest in this issue!
