### ISSUE TITLE
Code examples on reference section are displaying incorrectly

### ISSUE THREAD

**Issue by cosmopolitanwave** [processing/p5.js-website#552]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Mac OS

### Web browser and version

Chrome and Safari

### Actual Behavior

The code from this example produces an error:

<img width="1049" alt="Screen Shot 2024-09-16 at 11 54 34 PM" src="https://github.com/user-attachments/assets/5107b2da-1b60-43e4-91e1-371d4eefaa18">

### Expected Behavior

A working for loop

### Steps to reproduce

Go to website page:

https://p5js.org/reference/p5/for/

copy and paste the first for loop example into code editor

### Would you like to work on the issue?

I'm a code noob, so no thanks :)

**Comment by davepagurek** [comment]
We're also following this issue https://github.com/processing/p5.js-website/issues/447 and https://github.com/processing/p5.js-website/issues/522 I think 🙂

**Comment by davepagurek** [comment]
Fixed now from #554!
