### ISSUE TITLE
The parameter type is not displayed.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-website#564]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

None

### Actual Behavior

The parameter type is not displayed.
In mdx files with simple params, the parameter types are not displayed.
e.g. circle()

But an mdx file with overloads will show the parameter types.
e.g. line()

![スクリーンショット 2024-09-23 4 41 53](https://github.com/user-attachments/assets/8783dd2d-0321-42a9-8e7e-02b6c6217248)

### Expected Behavior

The parameter type is always displayed, with or without overloading.

### Steps to reproduce

open https://p5js.org/reference/p5/circle/ and https://p5js.org/reference/p5/line/ .
compare Parameters section.

### Would you like to work on the issue?

I will create PR

**Comment by davepagurek** [comment]
Resolved by #565
