### ISSUE TITLE
The order of the jump-to menus on the tutorial page is alphabetical.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-website#567]
### Most appropriate sections of the p5.js website?

Tutorials

### What is your operating system?

None

### Actual Behavior

The order of the jump-to menus on the tutorial page is alphabetical.

### Expected Behavior

The order of the jump-to menus on the tutorial page is the same as the order in which they are listed on https://p5js.org/tutorials/.

### Steps to reproduce

open https://p5js.org/tutorials/setting-up-your-environment/
see jumpTo menu on left side bar.

### Would you like to work on the issue?

I would make a pull request for improvement ideas.

**Comment by davepagurek** [comment]
@shibomb do you think any more changes are needed here, or are we free to close this issue now?

**Comment by shibomb** [comment]
@davepagurek 
If my implementation is OK, the problem is solved.
We have no problem with closing it.
Thank you!

**Comment by davepagurek** [comment]
It looks good to me 🙂 Thanks!
