### ISSUE TITLE
The JumpTo category name are appear in lowercase in the left sidebar of the example child page.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-website#585]
### Most appropriate sections of the p5.js website?

Examples

### What is your operating system?

None

### Actual Behavior

The JumpTo category name are appear in lowercase in the left sidebar of the example child page.
(It will not be translated in any language other than English.)

### Expected Behavior

Display the same as it appears on https://p5js.org/examples

### Steps to reproduce

open https://p5js.org/examples/shapes-and-color-shape-primitives/
see JumpTo link's category in left side bar.

compare with https://p5js.org/examples/

### Would you like to work on the issue?

I would create a pull request for suggestions.

**Comment by limzykenneth** [comment]
Fixed with #586
