### ISSUE TITLE
Remove Vertical Side Scroll Bar

### ISSUE THREAD

**Issue by prajwaln07** [processing/p5.js-website#596]
### Most appropriate sections of the p5.js website?

Home

### What is your operating system?

Windows

### Actual Behavior

vertical Side Scroll bar don't look good considering UI.
![Screenshot (96)](https://github.com/user-attachments/assets/eb68251e-f232-4f59-ae33-d70c7bcb9572)

### Expected Behavior

We can remove it ,It will look better without it

### Steps to reproduce

just go to main page and scroll downwards

### Would you like to work on the issue?

yes

**Comment by Dhanush111** [comment]
hey, can i contribute the solution here?

**Comment by prajwaln07** [comment]
> hey, can i contribute the solution here?

@Dhanush111  NO

**Comment by prajwaln07** [comment]
I would like to work on this issue please assign it to me

**Comment by davepagurek** [comment]
Hi everyone! Removing scrollbars altogether is an accessibility issue. [Here's an example of some guidelines when dealing with scrollbars.](https://adrianroselli.com/2019/01/baseline-rules-for-scrollbar-usability.html) It gets pretty complicated, and ultimately I think the best thing to do might just be to use what your browser/OS does natively and not interfere.
