### ISSUE TITLE
Typo in Docs: Reference > mult()

### ISSUE THREAD

**Issue by Zforgetaboutit** [processing/p5.js-website#601]
https://p5js.org/reference/p5.Vector/mult/

    "For example, v.mult(4, 5) multiplies v.x by, v.y by 5, and v.z by 1."

Should be

    "For example, v.mult(4, 5) multiplies v.x by **4**, v.y by 5, and v.z by 1."

**Comment by asukaminato0721** [comment]
it's because https://github.com/processing/p5.js/blob/78c4442d9cc77e849f3cdea3509fff99e3a26301/src/math/p5.Vector.js#L794
