### ISSUE TITLE
Reference for 'fill'

### ISSUE THREAD

**Issue by Jan1958x** [processing/p5.js-website#616]
### Topic

In the reference for 'fill' I am missing the description for 'alpha' including the range applicable for alpha.
Should this be added to the documentation of the reference?

**Comment by limzykenneth** [comment]
@nickmcintyre I think the description for the `alpha` parameter should be added on [this line](https://github.com/processing/p5.js/blob/main/src/color/setting.js#L1003)?

**Comment by Garima3110** [comment]
@limzykenneth I agree maybe we can have something like this here,
```  js
@param  {Number}   [alpha] optional alpha value, controls transparency (0 - transparent, 255 - opaque)
```
