### ISSUE TITLE
Canvas to show code in References not appearing

### ISSUE THREAD

**Issue by idkman9411** [processing/p5.js-website#621]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Windows

### Web browser and version

FireFox Version 132.0 (64-bit)

### Actual Behavior

When viewing any reference page, the canvas that shows what the example code does doesn't appear. Even when pressing the play button, refreshing the page, or restarting the computer, the canvas still doesn't appear. This also happens on Edge Version 130.0.2849.56 (Official build) (64-bit),  and Chrome Version 87.0.4280.88. I also tested this on a Mac with Chrome and Safari and this issue still occurs
![p5_canvas not working](https://github.com/user-attachments/assets/6d834a6e-2fd1-4732-ba70-f24e89dd1bc7)
When using Inspect, the main(and therefore canvas) is missing unlike the screenshot in Expected Behavior.
![p5_example not showing up](https://github.com/user-attachments/assets/82ead54c-6fb3-4977-ae2a-338f135e2476)

### Expected Behavior

The references show a canvas that showcases what the example code does. When using
![p5_example working](https://github.com/user-attachments/assets/36c5a7db-28e7-427c-ac41-f034aec418e9)
 Inspect, the HTML code shows the main with the canvas element in iframe div.

### Steps to reproduce

Go to[ p5.js.org](https://p5js.org/reference/) and click on any reference page

### Would you like to work on the issue?

No

**Comment by davepagurek** [comment]
Thanks for catching this, I had an extra change I needed to commit. Should work again as of https://github.com/processing/p5.js-website/pull/622!
