### ISSUE TITLE
Duplicate example on keyIsPressed reference page

### ISSUE THREAD

**Issue by Metamere** [processing/p5.js-website#642]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Windows

### Web browser and version

Chrome 131.0.6778.86

### Actual Behavior

There is a duplicated example. The first and second examples are identical.

### Expected Behavior

I was expecting to see unique examples, so I kept looking for a difference, and found none. The redundant example could be deleted, or else a third unique example could replace it.

### Steps to reproduce

Just go to https://p5js.org/reference/p5/keyIsPressed/ and you can see the issue.

### Would you like to work on the issue?

Yes

**Comment by Ved235** [comment]
Hi, can I work on this issue? I have a PR ready!
