### ISSUE TITLE
Add videos back to 2015 contributors conference

### ISSUE THREAD

**Issue by davepagurek** [processing/p5.js-website#656]
### Topic

Kate just pointed out that https://archive.p5js.org/community/contributors-conference-2015.html has some videos that are not present on https://p5js.org/events/contributors-conference-2015/. Maybe we can add those back?

**Comment by davepagurek** [comment]
We have a component to embed vimeo videos here https://github.com/processing/p5.js-website/blob/d7a6eaaf36a59d80f837a90f3652081cac5424e6/src/components/VimeoEmbed/index.astro that we could use, e.g. this for [this video](https://vimeo.com/129140298):
```jsx
<VimeoEmbed id="129140298" />
```

**Comment by Rishabh821** [comment]
Hi @davepagurek, 

I’d like to work on this issue! I’ll locate the missing videos from the archive page and use the `VimeoEmbed` component to add them back to the event page. 

Let me know if there are any specific guidelines or details I should follow.

Thanks!

**Comment by davepagurek** [comment]
Thanks @Rishabh821! I think we haven't tried using that component yet, so we can do whatever is simplest in order to get it working, like just stacking each video vertically on the page below the photos. Let me know if you run into any issues!

**Comment by Rishabh821** [comment]
@davepagurek,

I’ve completed the work for adding the missing videos to the Contributors Conference 2015 page. The PR is ready for review: [Link to the PR](https://github.com/processing/p5.js-website/pull/670))

Could you please take a look when you have a moment? Let me know if you need any changes or have any suggestions.
