### ISSUE TITLE
add link to issues on each reference page for reporting errors

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-website#70]

**Comment by GABBAR1947** [comment]
@lmccart I'd like to work on this. Can you elaborate this a bit.

**Comment by dhowe** [comment]
Excellent idea

**Comment by lmccart** [comment]
Currently, the processing reference includes a note on each page like this:
"If you see any errors or have suggestions, please let us [know](https://github.com/processing/processing-docs/issues?q=is%3Aopen)."

It would be great to do the same on each p5js.org reference page. The link could point here:
https://github.com/processing/p5.js/issues

Design-wise, it might make most sense at the bottom of each page, right after the class name listing, since there is already a lot going on visually at the top.

To make this change, you could start by editing this file:
https://github.com/processing/p5.js/blob/master/docs/yuidoc-p5-theme-src/scripts/tpl/itemEnd.html#L11
and following the instructions [here](https://github.com/processing/p5.js/wiki/Inline-documentation#generating-documentation) to rebuild the docs.

Thanks for tackling this!

**Comment by GABBAR1947** [comment]
@lmccart  Is this the only file to which i need to make the changes?

**Comment by lmccart** [comment]
yes

**Comment by GABBAR1947** [comment]
https://github.com/GABBAR1947/p5.js/blob/master/docs/yuidoc-p5-theme-src/scripts/tpl/itemEnd.html
@lmccart  check this out. Do we need some styling elements ?
