### ISSUE TITLE
Download Processing documentation

### ISSUE THREAD

**Issue by Piwakk** [processing/p5.js-website#81]
Hello,

I tried to download the whole reference found at p5js.org/reference, but it didn't work with ScrapBook, I think because of JavaScript. I then found this page: https://github.com/lmccart/p5.js/wiki/Inline-documentation#generating-documentation So, I installed npm, grunt, all the dependencies and everything needed, but I end up with an odd document that doesn't work either.

So, how could we get a stand-alone, off-line and convenient documentation, that doesn't rely on JavaScript? Actually, a plain HTML page that lists everything would be perfect.

Thanks in advance!

**Comment by taseenb** [comment]
The full reference is stored in a single JSON file: http://p5js.org/reference/data.json

That file is generated directly from the comments in the source code, and i think someone is making sure it is regularly updated. So you can use it to create any kind of document (or html page or pages).

**Comment by lmccart** [comment]
addressed in these issues:
https://github.com/processing/p5.js/issues/878
https://github.com/processing/p5.js-website/issues/143
