### ISSUE TITLE
Example Porting from the Processing.js page

### ISSUE THREAD

**Issue by juansrx** [processing/p5.js-website#86]
Hello

If you are still looking for ported examples from the processing.js page, I'd like to port these ones if you give me green light:

    Image Processing:
-----------------------------
    Pixel Array
    Brightness
    Blur
    Edge Detection
    Zoom
    Explode

    Motion:
---------------------
    Linear
    Bounce
    Bouncy Bubbles
    Moving On Curves
    Brownian

    Interaction:
-----------------
    Tickle
    Follow 1
    Follow 2
    Follow 3
    Reach 1
    Reach 2
    Reach 3

    Cellular Automata:
-------------------------------
    Spore 1
    Spore 2

    Fractals and L-Systems:
----------------------------------
    Mandelbrot
    Tree

Objects:
------------
Inheritance

I'm looking forward for any comment.

**Comment by shiffman** [comment]
Related to https://github.com/processing/processing-docs/issues/154 there are ports of some (all?) of these available at:

https://github.com/processing/processing-docs/tree/master/content/examples_p5

The plan for processing.org is to replace the animated web versions of examples with p5 behind the scenes so we can bring any of these over to p5js.org as well if we like!

**Comment by juansrx** [comment]
Ah!, ok, I'm closing this thread now.
