### ISSUE TITLE
Bugs on hello.p5js.org

### ISSUE THREAD

**Issue by zacharystenger** [processing/p5.js-website#87]
The Argument 1 of AudioParam error happened toward the end when there was audio attached to the mouse and I clicked and dragged the cursor back and forth over the left border where white meets dark gray.  
The weather.wind error didn't happen today but it happened a couple days ago when I took the screenshot.
![hellop5jsbugs](https://cloud.githubusercontent.com/assets/7537243/6991666/d546dbb4-da56-11e4-8b4d-42b1e2485d04.png)

**Comment by lmccart** [comment]
hey thanks @zacharystenger. do you mind reposting this one over here:
https://github.com/scottgarner/p5.js-video

**Comment by zacharystenger** [comment]
Sure. It's reposted.
