### ISSUE TITLE
Examples/Math/Arctangent

### ISSUE THREAD

**Issue by bobcgausa** [processing/p5.js-website#94]
starting port

**Comment by lmccart** [comment]
thanks @bobcgausa! see the documentation here for how to submit examples: https://github.com/processing/p5.js-website/wiki/Adding-examples

**Comment by shiffman** [comment]
If it's helpful to you, feel free to check out a bunch I've ported but haven't had time yet to bring over here:

https://github.com/processing/processing-docs/tree/master/content/examples_p5

Let me know if I can help!

**Comment by bobcgausa** [comment]
Daniel

Running NOC p5 toxic and box2d examples on Firefox. Several don,t run.
5/09.  5/12
Have they all been tested.
Bob
Professorcook.org

Sent from my Windows Phone
________________________________

**Comment by lmccart** [comment]
i believe this one has been added to the site
